<?xml version="1.0" encoding="utf-8"?>
<Database Name="2011-7-13GameCoreDB" Class="GameCoreDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=192.168.7.3;Initial Catalog=2011-7-13GameCoreDB;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="_2011_7_13GameCoreDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.T_BattleZone" Member="T_BattleZone">
    <Type Name="T_BattleZone">
      <Column Name="F_ZoneID" Type="System.Int16" DbType="SmallInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="F_ZoneName" Type="System.String" DbType="Char(16) NOT NULL" CanBeNull="false" />
      <Column Name="F_ZoneState" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="F_ZoneLine" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="F_ZoneAttrib" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="F_ChargeType" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="F_CurVersion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="F_BigZoneID" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.T_BattleLine" Member="T_BattleLine">
    <Type Name="T_BattleLine">
      <Column Name="F_NGSID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="F_Name" Type="System.String" DbType="Char(16) NOT NULL" CanBeNull="false" />
      <Column Name="F_ZoneID" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="F_MaxUser" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="F_Ip" Type="System.String" DbType="Char(32) NOT NULL" CanBeNull="false" />
      <Column Name="F_Port" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="F_State" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="F_DBISID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="F_PingPort" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.T_GameServer" Member="T_GameServer">
    <Type Name="T_GameServer">
      <Column Name="F_GSID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="F_IP" Type="System.String" DbType="Char(32) NOT NULL" CanBeNull="false" />
      <Column Name="F_GSNAME" Type="System.String" DbType="Char(16)" CanBeNull="true" />
      <Column Name="F_NGSID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="F_ZONEID" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="F_CampID" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="F_GSSceneID" Type="System.String" DbType="NChar(400) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>