//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSSWebService.LanguageResource {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GSSWebService.LanguageResource.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        internal static string Tip_Delete {
            get {
                return ResourceManager.GetString("Tip_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        internal static string Tip_DeleteStatue {
            get {
                return ResourceManager.GetString("Tip_DeleteStatue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏数据操作错误 的本地化字符串。
        /// </summary>
        internal static string Tip_GameDataOperateError {
            get {
                return ResourceManager.GetString("Tip_GameDataOperateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示:获取封停信息失败 的本地化字符串。
        /// </summary>
        internal static string Tip_GetCloseDownFailure {
            get {
                return ResourceManager.GetString("Tip_GetCloseDownFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 限制公告内容长度为300 的本地化字符串。
        /// </summary>
        internal static string Tip_LimitNoticeMsgLength {
            get {
                return ResourceManager.GetString("Tip_LimitNoticeMsgLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 否 的本地化字符串。
        /// </summary>
        internal static string Tip_No {
            get {
                return ResourceManager.GetString("Tip_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示:暂无封停信息 的本地化字符串。
        /// </summary>
        internal static string Tip_NoCloseDownInfo {
            get {
                return ResourceManager.GetString("Tip_NoCloseDownInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正常 的本地化字符串。
        /// </summary>
        internal static string Tip_NormalStatue {
            get {
                return ResourceManager.GetString("Tip_NormalStatue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有输入公告内容 的本地化字符串。
        /// </summary>
        internal static string Tip_NoticeMsgIsRequired {
            get {
                return ResourceManager.GetString("Tip_NoticeMsgIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 离线 的本地化字符串。
        /// </summary>
        internal static string Tip_Offline {
            get {
                return ResourceManager.GetString("Tip_Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在线 的本地化字符串。
        /// </summary>
        internal static string Tip_Online {
            get {
                return ResourceManager.GetString("Tip_Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非法请求，将拒绝对此请求提供服务 的本地化字符串。
        /// </summary>
        internal static string Tip_RequestServiceInvalid {
            get {
                return ResourceManager.GetString("Tip_RequestServiceInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是 的本地化字符串。
        /// </summary>
        internal static string Tip_Yes {
            get {
                return ResourceManager.GetString("Tip_Yes", resourceCulture);
            }
        }
    }
}
