//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.34209 版自动生成。
// 
#pragma warning disable 1591

namespace GSSGameWeb.WebServiceGSS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceGSSSoap", Namespace="http://tempuri.org/")]
    public partial class WebServiceGSS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback GameZoneToolLoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback GSSTaskAddOperationCompleted;
        
        private System.Threading.SendOrPostCallback GSSTaskAddRequstOperationCompleted;
        
        private System.Threading.SendOrPostCallback GSSCountDetailAddOperationCompleted;
        
        private System.Threading.SendOrPostCallback GSSTaskListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GSSMSGAddOperationCompleted;
        
        private System.Threading.SendOrPostCallback GSSMSGListOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebServiceGSS() {
            this.Url = global::GSSGameWeb.Properties.Settings.Default.GSSGameWeb_WebServiceGSS_WebServiceGSS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event GameZoneToolLoginCompletedEventHandler GameZoneToolLoginCompleted;
        
        /// <remarks/>
        public event GSSTaskAddCompletedEventHandler GSSTaskAddCompleted;
        
        /// <remarks/>
        public event GSSTaskAddRequstCompletedEventHandler GSSTaskAddRequstCompleted;
        
        /// <remarks/>
        public event GSSCountDetailAddCompletedEventHandler GSSCountDetailAddCompleted;
        
        /// <remarks/>
        public event GSSTaskListCompletedEventHandler GSSTaskListCompleted;
        
        /// <remarks/>
        public event GSSMSGAddCompletedEventHandler GSSMSGAddCompleted;
        
        /// <remarks/>
        public event GSSMSGListCompletedEventHandler GSSMSGListCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GameZoneToolLogin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GameZoneToolLogin(string username, string password) {
            object[] results = this.Invoke("GameZoneToolLogin", new object[] {
                        username,
                        password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GameZoneToolLoginAsync(string username, string password) {
            this.GameZoneToolLoginAsync(username, password, null);
        }
        
        /// <remarks/>
        public void GameZoneToolLoginAsync(string username, string password, object userState) {
            if ((this.GameZoneToolLoginOperationCompleted == null)) {
                this.GameZoneToolLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGameZoneToolLoginOperationCompleted);
            }
            this.InvokeAsync("GameZoneToolLogin", new object[] {
                        username,
                        password}, this.GameZoneToolLoginOperationCompleted, userState);
        }
        
        private void OnGameZoneToolLoginOperationCompleted(object arg) {
            if ((this.GameZoneToolLoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GameZoneToolLoginCompleted(this, new GameZoneToolLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GSSTaskAdd", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GSSTaskAdd(string type, string note, string qq, string mobile, string gdata, string file) {
            object[] results = this.Invoke("GSSTaskAdd", new object[] {
                        type,
                        note,
                        qq,
                        mobile,
                        gdata,
                        file});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GSSTaskAddAsync(string type, string note, string qq, string mobile, string gdata, string file) {
            this.GSSTaskAddAsync(type, note, qq, mobile, gdata, file, null);
        }
        
        /// <remarks/>
        public void GSSTaskAddAsync(string type, string note, string qq, string mobile, string gdata, string file, object userState) {
            if ((this.GSSTaskAddOperationCompleted == null)) {
                this.GSSTaskAddOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGSSTaskAddOperationCompleted);
            }
            this.InvokeAsync("GSSTaskAdd", new object[] {
                        type,
                        note,
                        qq,
                        mobile,
                        gdata,
                        file}, this.GSSTaskAddOperationCompleted, userState);
        }
        
        private void OnGSSTaskAddOperationCompleted(object arg) {
            if ((this.GSSTaskAddCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GSSTaskAddCompleted(this, new GSSTaskAddCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GSSTaskAddRequst", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GSSTaskAddRequst(string gdata, string answer) {
            object[] results = this.Invoke("GSSTaskAddRequst", new object[] {
                        gdata,
                        answer});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GSSTaskAddRequstAsync(string gdata, string answer) {
            this.GSSTaskAddRequstAsync(gdata, answer, null);
        }
        
        /// <remarks/>
        public void GSSTaskAddRequstAsync(string gdata, string answer, object userState) {
            if ((this.GSSTaskAddRequstOperationCompleted == null)) {
                this.GSSTaskAddRequstOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGSSTaskAddRequstOperationCompleted);
            }
            this.InvokeAsync("GSSTaskAddRequst", new object[] {
                        gdata,
                        answer}, this.GSSTaskAddRequstOperationCompleted, userState);
        }
        
        private void OnGSSTaskAddRequstOperationCompleted(object arg) {
            if ((this.GSSTaskAddRequstCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GSSTaskAddRequstCompleted(this, new GSSTaskAddRequstCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GSSCountDetailAdd", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GSSCountDetailAdd(CountDetail model) {
            object[] results = this.Invoke("GSSCountDetailAdd", new object[] {
                        model});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GSSCountDetailAddAsync(CountDetail model) {
            this.GSSCountDetailAddAsync(model, null);
        }
        
        /// <remarks/>
        public void GSSCountDetailAddAsync(CountDetail model, object userState) {
            if ((this.GSSCountDetailAddOperationCompleted == null)) {
                this.GSSCountDetailAddOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGSSCountDetailAddOperationCompleted);
            }
            this.InvokeAsync("GSSCountDetailAdd", new object[] {
                        model}, this.GSSCountDetailAddOperationCompleted, userState);
        }
        
        private void OnGSSCountDetailAddOperationCompleted(object arg) {
            if ((this.GSSCountDetailAddCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GSSCountDetailAddCompleted(this, new GSSCountDetailAddCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GSSTaskList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GSSTaskList(string userid) {
            object[] results = this.Invoke("GSSTaskList", new object[] {
                        userid});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GSSTaskListAsync(string userid) {
            this.GSSTaskListAsync(userid, null);
        }
        
        /// <remarks/>
        public void GSSTaskListAsync(string userid, object userState) {
            if ((this.GSSTaskListOperationCompleted == null)) {
                this.GSSTaskListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGSSTaskListOperationCompleted);
            }
            this.InvokeAsync("GSSTaskList", new object[] {
                        userid}, this.GSSTaskListOperationCompleted, userState);
        }
        
        private void OnGSSTaskListOperationCompleted(object arg) {
            if ((this.GSSTaskListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GSSTaskListCompleted(this, new GSSTaskListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GSSMSGAdd", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GSSMSGAdd(string note, string gdata) {
            object[] results = this.Invoke("GSSMSGAdd", new object[] {
                        note,
                        gdata});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GSSMSGAddAsync(string note, string gdata) {
            this.GSSMSGAddAsync(note, gdata, null);
        }
        
        /// <remarks/>
        public void GSSMSGAddAsync(string note, string gdata, object userState) {
            if ((this.GSSMSGAddOperationCompleted == null)) {
                this.GSSMSGAddOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGSSMSGAddOperationCompleted);
            }
            this.InvokeAsync("GSSMSGAdd", new object[] {
                        note,
                        gdata}, this.GSSMSGAddOperationCompleted, userState);
        }
        
        private void OnGSSMSGAddOperationCompleted(object arg) {
            if ((this.GSSMSGAddCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GSSMSGAddCompleted(this, new GSSMSGAddCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GSSMSGList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GSSMSGList(string roleid) {
            object[] results = this.Invoke("GSSMSGList", new object[] {
                        roleid});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GSSMSGListAsync(string roleid) {
            this.GSSMSGListAsync(roleid, null);
        }
        
        /// <remarks/>
        public void GSSMSGListAsync(string roleid, object userState) {
            if ((this.GSSMSGListOperationCompleted == null)) {
                this.GSSMSGListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGSSMSGListOperationCompleted);
            }
            this.InvokeAsync("GSSMSGList", new object[] {
                        roleid}, this.GSSMSGListOperationCompleted, userState);
        }
        
        private void OnGSSMSGListOperationCompleted(object arg) {
            if ((this.GSSMSGListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GSSMSGListCompleted(this, new GSSMSGListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CountDetail {
        
        private int screenwidthField;
        
        private int screenheightField;
        
        private long idField;
        
        private System.Nullable<int> yearField;
        
        private System.Nullable<int> monthField;
        
        private System.Nullable<int> dayField;
        
        private System.Nullable<int> hourField;
        
        private System.Nullable<int> gameField;
        
        private System.Nullable<int> typeField;
        
        private string pageField;
        
        private string ipField;
        
        private string iESoftField;
        
        private string osField;
        
        private string cLRField;
        
        private string languageField;
        
        private string winBitField;
        
        private System.Nullable<System.DateTime> timeField;
        
        /// <remarks/>
        public int Screenwidth {
            get {
                return this.screenwidthField;
            }
            set {
                this.screenwidthField = value;
            }
        }
        
        /// <remarks/>
        public int Screenheight {
            get {
                return this.screenheightField;
            }
            set {
                this.screenheightField = value;
            }
        }
        
        /// <remarks/>
        public long ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Month {
            get {
                return this.monthField;
            }
            set {
                this.monthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Day {
            get {
                return this.dayField;
            }
            set {
                this.dayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Hour {
            get {
                return this.hourField;
            }
            set {
                this.hourField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Game {
            get {
                return this.gameField;
            }
            set {
                this.gameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string Page {
            get {
                return this.pageField;
            }
            set {
                this.pageField = value;
            }
        }
        
        /// <remarks/>
        public string IP {
            get {
                return this.ipField;
            }
            set {
                this.ipField = value;
            }
        }
        
        /// <remarks/>
        public string IESoft {
            get {
                return this.iESoftField;
            }
            set {
                this.iESoftField = value;
            }
        }
        
        /// <remarks/>
        public string OS {
            get {
                return this.osField;
            }
            set {
                this.osField = value;
            }
        }
        
        /// <remarks/>
        public string CLR {
            get {
                return this.cLRField;
            }
            set {
                this.cLRField = value;
            }
        }
        
        /// <remarks/>
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        public string WinBit {
            get {
                return this.winBitField;
            }
            set {
                this.winBitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GameZoneToolLoginCompletedEventHandler(object sender, GameZoneToolLoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GameZoneToolLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GameZoneToolLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GSSTaskAddCompletedEventHandler(object sender, GSSTaskAddCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GSSTaskAddCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GSSTaskAddCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GSSTaskAddRequstCompletedEventHandler(object sender, GSSTaskAddRequstCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GSSTaskAddRequstCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GSSTaskAddRequstCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GSSCountDetailAddCompletedEventHandler(object sender, GSSCountDetailAddCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GSSCountDetailAddCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GSSCountDetailAddCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GSSTaskListCompletedEventHandler(object sender, GSSTaskListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GSSTaskListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GSSTaskListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GSSMSGAddCompletedEventHandler(object sender, GSSMSGAddCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GSSMSGAddCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GSSMSGAddCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GSSMSGListCompletedEventHandler(object sender, GSSMSGListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GSSMSGListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GSSMSGListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591