//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSS.Web.Notfiy {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblF_ID;
		protected global::System.Web.UI.WebControls.TextBox txtF_Title;
		protected global::System.Web.UI.WebControls.TextBox txtF_Note;
		protected global::System.Web.UI.WebControls.TextBox txtF_URL;
		protected global::System.Web.UI.WebControls.TextBox txtF_DateTime;
		protected global::System.Web.UI.WebControls.TextBox txtF_SeeTime;
		protected global::System.Web.UI.WebControls.CheckBox chkF_IsSeed;
		protected global::System.Web.UI.WebControls.TextBox txtF_UserID;
		protected global::System.Web.UI.WebControls.TextBox txtF_Type;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
