//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSS.Web.Tasks {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblF_ID;
	protected global::System.Web.UI.WebControls.Label lblF_Title;
	protected global::System.Web.UI.WebControls.Label lblF_Note;
	protected global::System.Web.UI.WebControls.Label lblF_From;
	protected global::System.Web.UI.WebControls.Label lblF_Type;
	protected global::System.Web.UI.WebControls.Label lblF_JinjiLevel;
	protected global::System.Web.UI.WebControls.Label lblF_GameName;
	protected global::System.Web.UI.WebControls.Label lblF_GameZone;
	protected global::System.Web.UI.WebControls.Label lblF_GUserID;
	protected global::System.Web.UI.WebControls.Label lblF_GRoleName;
	protected global::System.Web.UI.WebControls.Label lblF_Tag;
	protected global::System.Web.UI.WebControls.Label lblF_DateTime;
	protected global::System.Web.UI.WebControls.Label lblF_State;
	protected global::System.Web.UI.WebControls.Label lblF_Telphone;
	protected global::System.Web.UI.WebControls.Label lblF_DutyMan;


       
    }
}
