//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSSUI.LanguageResource {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GSSUI.LanguageResource.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        internal static string BtnCancel {
            get {
                return ResourceManager.GetString("BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消窗体最前 的本地化字符串。
        /// </summary>
        internal static string BtnCancelFormFirst {
            get {
                return ResourceManager.GetString("BtnCancelFormFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        internal static string BtnClose {
            get {
                return ResourceManager.GetString("BtnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制 的本地化字符串。
        /// </summary>
        internal static string BtnCopy {
            get {
                return ResourceManager.GetString("BtnCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 剪切 的本地化字符串。
        /// </summary>
        internal static string BtnCut {
            get {
                return ResourceManager.GetString("BtnCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        internal static string BtnDelete {
            get {
                return ResourceManager.GetString("BtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最大化 的本地化字符串。
        /// </summary>
        internal static string BtnMax {
            get {
                return ResourceManager.GetString("BtnMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最小化 的本地化字符串。
        /// </summary>
        internal static string BtnMin {
            get {
                return ResourceManager.GetString("BtnMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 否 的本地化字符串。
        /// </summary>
        internal static string BtnNo {
            get {
                return ResourceManager.GetString("BtnNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 粘贴 的本地化字符串。
        /// </summary>
        internal static string BtnPaste {
            get {
                return ResourceManager.GetString("BtnPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 还原 的本地化字符串。
        /// </summary>
        internal static string BtnRestore {
            get {
                return ResourceManager.GetString("BtnRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全选 的本地化字符串。
        /// </summary>
        internal static string BtnSelectAll {
            get {
                return ResourceManager.GetString("BtnSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置窗体最前 的本地化字符串。
        /// </summary>
        internal static string BtnSetFormFirst {
            get {
                return ResourceManager.GetString("BtnSetFormFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        internal static string BtnSure {
            get {
                return ResourceManager.GetString("BtnSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是 的本地化字符串。
        /// </summary>
        internal static string BtnYes {
            get {
                return ResourceManager.GetString("BtnYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认皮肤 的本地化字符串。
        /// </summary>
        internal static string LblDefaultSkin {
            get {
                return ResourceManager.GetString("LblDefaultSkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每页 的本地化字符串。
        /// </summary>
        internal static string LblEachPage {
            get {
                return ResourceManager.GetString("LblEachPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 跳转 的本地化字符串。
        /// </summary>
        internal static string LblGoto {
            get {
                return ResourceManager.GetString("LblGoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 首页 的本地化字符串。
        /// </summary>
        internal static string LblHome {
            get {
                return ResourceManager.GetString("LblHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下一页 的本地化字符串。
        /// </summary>
        internal static string LblNext {
            get {
                return ResourceManager.GetString("LblNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上一页 的本地化字符串。
        /// </summary>
        internal static string LblPrevious {
            get {
                return ResourceManager.GetString("LblPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 条记录 的本地化字符串。
        /// </summary>
        internal static string LblRecords {
            get {
                return ResourceManager.GetString("LblRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尾页 的本地化字符串。
        /// </summary>
        internal static string LblShadowe {
            get {
                return ResourceManager.GetString("LblShadowe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 条 的本地化字符串。
        /// </summary>
        internal static string LblStrip {
            get {
                return ResourceManager.GetString("LblStrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 共 的本地化字符串。
        /// </summary>
        internal static string LblTotal {
            get {
                return ResourceManager.GetString("LblTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调整窗体透明度 的本地化字符串。
        /// </summary>
        internal static string Tip_ChangeFormOpacity {
            get {
                return ResourceManager.GetString("Tip_ChangeFormOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调整透明度(最小为10) 的本地化字符串。
        /// </summary>
        internal static string Tip_ChangeOpacityWithMin {
            get {
                return ResourceManager.GetString("Tip_ChangeOpacityWithMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 颜色 的本地化字符串。
        /// </summary>
        internal static string Tip_Color {
            get {
                return ResourceManager.GetString("Tip_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 皮肤 的本地化字符串。
        /// </summary>
        internal static string Tip_Skin {
            get {
                return ResourceManager.GetString("Tip_Skin", resourceCulture);
            }
        }
    }
}
