//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSS.Web.Users {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtF_UserName;
		protected global::System.Web.UI.WebControls.TextBox txtF_PassWord;
		protected global::System.Web.UI.WebControls.TextBox txtF_DepartID;
		protected global::System.Web.UI.WebControls.TextBox txtF_RoleID;
		protected global::System.Web.UI.WebControls.CheckBox chkF_Sex;
		protected global::System.Web.UI.WebControls.TextBox txtF_Birthday;
		protected global::System.Web.UI.WebControls.TextBox txtF_Email;
		protected global::System.Web.UI.WebControls.TextBox txtF_MobilePhone;
		protected global::System.Web.UI.WebControls.TextBox txtF_RegTime;
		protected global::System.Web.UI.WebControls.TextBox txtF_LastInTime;
		protected global::System.Web.UI.WebControls.CheckBox chkF_IsUsed;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
