//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSS.Web.Users {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblF_UserID;
	protected global::System.Web.UI.WebControls.Label lblF_UserName;
	protected global::System.Web.UI.WebControls.Label lblF_PassWord;
	protected global::System.Web.UI.WebControls.Label lblF_DepartID;
	protected global::System.Web.UI.WebControls.Label lblF_RoleID;
	protected global::System.Web.UI.WebControls.Label lblF_Sex;
	protected global::System.Web.UI.WebControls.Label lblF_Birthday;
	protected global::System.Web.UI.WebControls.Label lblF_Email;
	protected global::System.Web.UI.WebControls.Label lblF_MobilePhone;
	protected global::System.Web.UI.WebControls.Label lblF_RegTime;
	protected global::System.Web.UI.WebControls.Label lblF_LastInTime;
	protected global::System.Web.UI.WebControls.Label lblF_IsUsed;


       
    }
}
