//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace GSSServer.WebServiceGame {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceXLJSoap", Namespace="http://tempuri.org/")]
    public partial class ServiceXLJ : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetGameUsersCOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetGameRoleCROperationCompleted;
        
        private System.Threading.SendOrPostCallback GetGameRoleCOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetZoneLineOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetUserLockOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetRoleLockOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetUserNoLockOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetRoleNoLockOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLockInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetUserGMUseOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetUserGMBackOperationCompleted;
        
        private System.Threading.SendOrPostCallback RoleNameChangeOperationCompleted;
        
        private System.Threading.SendOrPostCallback RoleZoneChangeOperationCompleted;
        
        private System.Threading.SendOrPostCallback UserRoleClearOnlineOperationCompleted;
        
        private System.Threading.SendOrPostCallback ClearChildDisInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GameNoticeStopOperationCompleted;
        
        private System.Threading.SendOrPostCallback GameNoticeStartOperationCompleted;
        
        private System.Threading.SendOrPostCallback GameGiftAwardDoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GameGiftAwardDoFor5NumOperationCompleted;
        
        private System.Threading.SendOrPostCallback GameGiftUserAddOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteFullServiceEmailOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddDisChatOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServiceXLJ() {
            this.Url = global::GSSServer.Properties.Settings.Default.GSSServer_WebServiceGame_ServiceXLJ;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event GetGameUsersCCompletedEventHandler GetGameUsersCCompleted;
        
        /// <remarks/>
        public event GetGameRoleCRCompletedEventHandler GetGameRoleCRCompleted;
        
        /// <remarks/>
        public event GetGameRoleCCompletedEventHandler GetGameRoleCCompleted;
        
        /// <remarks/>
        public event GetZoneLineCompletedEventHandler GetZoneLineCompleted;
        
        /// <remarks/>
        public event SetUserLockCompletedEventHandler SetUserLockCompleted;
        
        /// <remarks/>
        public event SetRoleLockCompletedEventHandler SetRoleLockCompleted;
        
        /// <remarks/>
        public event SetUserNoLockCompletedEventHandler SetUserNoLockCompleted;
        
        /// <remarks/>
        public event SetRoleNoLockCompletedEventHandler SetRoleNoLockCompleted;
        
        /// <remarks/>
        public event GetLockInfoCompletedEventHandler GetLockInfoCompleted;
        
        /// <remarks/>
        public event SetUserGMUseCompletedEventHandler SetUserGMUseCompleted;
        
        /// <remarks/>
        public event SetUserGMBackCompletedEventHandler SetUserGMBackCompleted;
        
        /// <remarks/>
        public event RoleNameChangeCompletedEventHandler RoleNameChangeCompleted;
        
        /// <remarks/>
        public event RoleZoneChangeCompletedEventHandler RoleZoneChangeCompleted;
        
        /// <remarks/>
        public event UserRoleClearOnlineCompletedEventHandler UserRoleClearOnlineCompleted;
        
        /// <remarks/>
        public event ClearChildDisInfoCompletedEventHandler ClearChildDisInfoCompleted;
        
        /// <remarks/>
        public event GameNoticeStopCompletedEventHandler GameNoticeStopCompleted;
        
        /// <remarks/>
        public event GameNoticeStartCompletedEventHandler GameNoticeStartCompleted;
        
        /// <remarks/>
        public event GameGiftAwardDoCompletedEventHandler GameGiftAwardDoCompleted;
        
        /// <remarks/>
        public event GameGiftAwardDoFor5NumCompletedEventHandler GameGiftAwardDoFor5NumCompleted;
        
        /// <remarks/>
        public event GameGiftUserAddCompletedEventHandler GameGiftUserAddCompleted;
        
        /// <remarks/>
        public event DeleteFullServiceEmailCompletedEventHandler DeleteFullServiceEmailCompleted;
        
        /// <remarks/>
        public event AddDisChatCompletedEventHandler AddDisChatCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetGameUsersC", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GetGameUsersC(string query) {
            object[] results = this.Invoke("GetGameUsersC", new object[] {
                        query});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void GetGameUsersCAsync(string query) {
            this.GetGameUsersCAsync(query, null);
        }
        
        /// <remarks/>
        public void GetGameUsersCAsync(string query, object userState) {
            if ((this.GetGameUsersCOperationCompleted == null)) {
                this.GetGameUsersCOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGameUsersCOperationCompleted);
            }
            this.InvokeAsync("GetGameUsersC", new object[] {
                        query}, this.GetGameUsersCOperationCompleted, userState);
        }
        
        private void OnGetGameUsersCOperationCompleted(object arg) {
            if ((this.GetGameUsersCCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGameUsersCCompleted(this, new GetGameUsersCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetGameRoleCR", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GetGameRoleCR(string whereStr) {
            object[] results = this.Invoke("GetGameRoleCR", new object[] {
                        whereStr});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void GetGameRoleCRAsync(string whereStr) {
            this.GetGameRoleCRAsync(whereStr, null);
        }
        
        /// <remarks/>
        public void GetGameRoleCRAsync(string whereStr, object userState) {
            if ((this.GetGameRoleCROperationCompleted == null)) {
                this.GetGameRoleCROperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGameRoleCROperationCompleted);
            }
            this.InvokeAsync("GetGameRoleCR", new object[] {
                        whereStr}, this.GetGameRoleCROperationCompleted, userState);
        }
        
        private void OnGetGameRoleCROperationCompleted(object arg) {
            if ((this.GetGameRoleCRCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGameRoleCRCompleted(this, new GetGameRoleCRCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetGameRoleC", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GetGameRoleC(string userid) {
            object[] results = this.Invoke("GetGameRoleC", new object[] {
                        userid});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void GetGameRoleCAsync(string userid) {
            this.GetGameRoleCAsync(userid, null);
        }
        
        /// <remarks/>
        public void GetGameRoleCAsync(string userid, object userState) {
            if ((this.GetGameRoleCOperationCompleted == null)) {
                this.GetGameRoleCOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGameRoleCOperationCompleted);
            }
            this.InvokeAsync("GetGameRoleC", new object[] {
                        userid}, this.GetGameRoleCOperationCompleted, userState);
        }
        
        private void OnGetGameRoleCOperationCompleted(object arg) {
            if ((this.GetGameRoleCCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGameRoleCCompleted(this, new GetGameRoleCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetZoneLine", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GetZoneLine() {
            object[] results = this.Invoke("GetZoneLine", new object[0]);
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void GetZoneLineAsync() {
            this.GetZoneLineAsync(null);
        }
        
        /// <remarks/>
        public void GetZoneLineAsync(object userState) {
            if ((this.GetZoneLineOperationCompleted == null)) {
                this.GetZoneLineOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetZoneLineOperationCompleted);
            }
            this.InvokeAsync("GetZoneLine", new object[0], this.GetZoneLineOperationCompleted, userState);
        }
        
        private void OnGetZoneLineOperationCompleted(object arg) {
            if ((this.GetZoneLineCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetZoneLineCompleted(this, new GetZoneLineCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SetUserLock", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SetUserLock(string userid, string username, string locktype, string locktime) {
            object[] results = this.Invoke("SetUserLock", new object[] {
                        userid,
                        username,
                        locktype,
                        locktime});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SetUserLockAsync(string userid, string username, string locktype, string locktime) {
            this.SetUserLockAsync(userid, username, locktype, locktime, null);
        }
        
        /// <remarks/>
        public void SetUserLockAsync(string userid, string username, string locktype, string locktime, object userState) {
            if ((this.SetUserLockOperationCompleted == null)) {
                this.SetUserLockOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetUserLockOperationCompleted);
            }
            this.InvokeAsync("SetUserLock", new object[] {
                        userid,
                        username,
                        locktype,
                        locktime}, this.SetUserLockOperationCompleted, userState);
        }
        
        private void OnSetUserLockOperationCompleted(object arg) {
            if ((this.SetUserLockCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetUserLockCompleted(this, new SetUserLockCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SetRoleLock", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SetRoleLock(string roleid, string rolename, string locktype, string locktime) {
            object[] results = this.Invoke("SetRoleLock", new object[] {
                        roleid,
                        rolename,
                        locktype,
                        locktime});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SetRoleLockAsync(string roleid, string rolename, string locktype, string locktime) {
            this.SetRoleLockAsync(roleid, rolename, locktype, locktime, null);
        }
        
        /// <remarks/>
        public void SetRoleLockAsync(string roleid, string rolename, string locktype, string locktime, object userState) {
            if ((this.SetRoleLockOperationCompleted == null)) {
                this.SetRoleLockOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetRoleLockOperationCompleted);
            }
            this.InvokeAsync("SetRoleLock", new object[] {
                        roleid,
                        rolename,
                        locktype,
                        locktime}, this.SetRoleLockOperationCompleted, userState);
        }
        
        private void OnSetRoleLockOperationCompleted(object arg) {
            if ((this.SetRoleLockCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetRoleLockCompleted(this, new SetRoleLockCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SetUserNoLock", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SetUserNoLock(string userid) {
            object[] results = this.Invoke("SetUserNoLock", new object[] {
                        userid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SetUserNoLockAsync(string userid) {
            this.SetUserNoLockAsync(userid, null);
        }
        
        /// <remarks/>
        public void SetUserNoLockAsync(string userid, object userState) {
            if ((this.SetUserNoLockOperationCompleted == null)) {
                this.SetUserNoLockOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetUserNoLockOperationCompleted);
            }
            this.InvokeAsync("SetUserNoLock", new object[] {
                        userid}, this.SetUserNoLockOperationCompleted, userState);
        }
        
        private void OnSetUserNoLockOperationCompleted(object arg) {
            if ((this.SetUserNoLockCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetUserNoLockCompleted(this, new SetUserNoLockCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SetRoleNoLock", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SetRoleNoLock(string roleid) {
            object[] results = this.Invoke("SetRoleNoLock", new object[] {
                        roleid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SetRoleNoLockAsync(string roleid) {
            this.SetRoleNoLockAsync(roleid, null);
        }
        
        /// <remarks/>
        public void SetRoleNoLockAsync(string roleid, object userState) {
            if ((this.SetRoleNoLockOperationCompleted == null)) {
                this.SetRoleNoLockOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetRoleNoLockOperationCompleted);
            }
            this.InvokeAsync("SetRoleNoLock", new object[] {
                        roleid}, this.SetRoleNoLockOperationCompleted, userState);
        }
        
        private void OnSetRoleNoLockOperationCompleted(object arg) {
            if ((this.SetRoleNoLockCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetRoleNoLockCompleted(this, new SetRoleNoLockCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetLockInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetLockInfo(string userid, string roleid) {
            object[] results = this.Invoke("GetLockInfo", new object[] {
                        userid,
                        roleid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetLockInfoAsync(string userid, string roleid) {
            this.GetLockInfoAsync(userid, roleid, null);
        }
        
        /// <remarks/>
        public void GetLockInfoAsync(string userid, string roleid, object userState) {
            if ((this.GetLockInfoOperationCompleted == null)) {
                this.GetLockInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLockInfoOperationCompleted);
            }
            this.InvokeAsync("GetLockInfo", new object[] {
                        userid,
                        roleid}, this.GetLockInfoOperationCompleted, userState);
        }
        
        private void OnGetLockInfoOperationCompleted(object arg) {
            if ((this.GetLockInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLockInfoCompleted(this, new GetLockInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SetUserGMUse", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SetUserGMUse(string userid, string newuserpsw, string gmname) {
            object[] results = this.Invoke("SetUserGMUse", new object[] {
                        userid,
                        newuserpsw,
                        gmname});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SetUserGMUseAsync(string userid, string newuserpsw, string gmname) {
            this.SetUserGMUseAsync(userid, newuserpsw, gmname, null);
        }
        
        /// <remarks/>
        public void SetUserGMUseAsync(string userid, string newuserpsw, string gmname, object userState) {
            if ((this.SetUserGMUseOperationCompleted == null)) {
                this.SetUserGMUseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetUserGMUseOperationCompleted);
            }
            this.InvokeAsync("SetUserGMUse", new object[] {
                        userid,
                        newuserpsw,
                        gmname}, this.SetUserGMUseOperationCompleted, userState);
        }
        
        private void OnSetUserGMUseOperationCompleted(object arg) {
            if ((this.SetUserGMUseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetUserGMUseCompleted(this, new SetUserGMUseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SetUserGMBack", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SetUserGMBack(string userid) {
            object[] results = this.Invoke("SetUserGMBack", new object[] {
                        userid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SetUserGMBackAsync(string userid) {
            this.SetUserGMBackAsync(userid, null);
        }
        
        /// <remarks/>
        public void SetUserGMBackAsync(string userid, object userState) {
            if ((this.SetUserGMBackOperationCompleted == null)) {
                this.SetUserGMBackOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetUserGMBackOperationCompleted);
            }
            this.InvokeAsync("SetUserGMBack", new object[] {
                        userid}, this.SetUserGMBackOperationCompleted, userState);
        }
        
        private void OnSetUserGMBackOperationCompleted(object arg) {
            if ((this.SetUserGMBackCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetUserGMBackCompleted(this, new SetUserGMBackCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RoleNameChange", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RoleNameChange(int userid, int roleid, string rolename, string newrolename) {
            object[] results = this.Invoke("RoleNameChange", new object[] {
                        userid,
                        roleid,
                        rolename,
                        newrolename});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RoleNameChangeAsync(int userid, int roleid, string rolename, string newrolename) {
            this.RoleNameChangeAsync(userid, roleid, rolename, newrolename, null);
        }
        
        /// <remarks/>
        public void RoleNameChangeAsync(int userid, int roleid, string rolename, string newrolename, object userState) {
            if ((this.RoleNameChangeOperationCompleted == null)) {
                this.RoleNameChangeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRoleNameChangeOperationCompleted);
            }
            this.InvokeAsync("RoleNameChange", new object[] {
                        userid,
                        roleid,
                        rolename,
                        newrolename}, this.RoleNameChangeOperationCompleted, userState);
        }
        
        private void OnRoleNameChangeOperationCompleted(object arg) {
            if ((this.RoleNameChangeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RoleNameChangeCompleted(this, new RoleNameChangeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RoleZoneChange", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RoleZoneChange(int userid, int roleid, int zoneid) {
            object[] results = this.Invoke("RoleZoneChange", new object[] {
                        userid,
                        roleid,
                        zoneid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RoleZoneChangeAsync(int userid, int roleid, int zoneid) {
            this.RoleZoneChangeAsync(userid, roleid, zoneid, null);
        }
        
        /// <remarks/>
        public void RoleZoneChangeAsync(int userid, int roleid, int zoneid, object userState) {
            if ((this.RoleZoneChangeOperationCompleted == null)) {
                this.RoleZoneChangeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRoleZoneChangeOperationCompleted);
            }
            this.InvokeAsync("RoleZoneChange", new object[] {
                        userid,
                        roleid,
                        zoneid}, this.RoleZoneChangeOperationCompleted, userState);
        }
        
        private void OnRoleZoneChangeOperationCompleted(object arg) {
            if ((this.RoleZoneChangeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RoleZoneChangeCompleted(this, new RoleZoneChangeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UserRoleClearOnline", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UserRoleClearOnline(int userid) {
            object[] results = this.Invoke("UserRoleClearOnline", new object[] {
                        userid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UserRoleClearOnlineAsync(int userid) {
            this.UserRoleClearOnlineAsync(userid, null);
        }
        
        /// <remarks/>
        public void UserRoleClearOnlineAsync(int userid, object userState) {
            if ((this.UserRoleClearOnlineOperationCompleted == null)) {
                this.UserRoleClearOnlineOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserRoleClearOnlineOperationCompleted);
            }
            this.InvokeAsync("UserRoleClearOnline", new object[] {
                        userid}, this.UserRoleClearOnlineOperationCompleted, userState);
        }
        
        private void OnUserRoleClearOnlineOperationCompleted(object arg) {
            if ((this.UserRoleClearOnlineCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UserRoleClearOnlineCompleted(this, new UserRoleClearOnlineCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ClearChildDisInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ClearChildDisInfo(string userid) {
            object[] results = this.Invoke("ClearChildDisInfo", new object[] {
                        userid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ClearChildDisInfoAsync(string userid) {
            this.ClearChildDisInfoAsync(userid, null);
        }
        
        /// <remarks/>
        public void ClearChildDisInfoAsync(string userid, object userState) {
            if ((this.ClearChildDisInfoOperationCompleted == null)) {
                this.ClearChildDisInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnClearChildDisInfoOperationCompleted);
            }
            this.InvokeAsync("ClearChildDisInfo", new object[] {
                        userid}, this.ClearChildDisInfoOperationCompleted, userState);
        }
        
        private void OnClearChildDisInfoOperationCompleted(object arg) {
            if ((this.ClearChildDisInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ClearChildDisInfoCompleted(this, new ClearChildDisInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GameNoticeStop", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GameNoticeStop(string taskid) {
            object[] results = this.Invoke("GameNoticeStop", new object[] {
                        taskid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GameNoticeStopAsync(string taskid) {
            this.GameNoticeStopAsync(taskid, null);
        }
        
        /// <remarks/>
        public void GameNoticeStopAsync(string taskid, object userState) {
            if ((this.GameNoticeStopOperationCompleted == null)) {
                this.GameNoticeStopOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGameNoticeStopOperationCompleted);
            }
            this.InvokeAsync("GameNoticeStop", new object[] {
                        taskid}, this.GameNoticeStopOperationCompleted, userState);
        }
        
        private void OnGameNoticeStopOperationCompleted(object arg) {
            if ((this.GameNoticeStopCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GameNoticeStopCompleted(this, new GameNoticeStopCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GameNoticeStart", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GameNoticeStart(string taskid, string area, string msg) {
            object[] results = this.Invoke("GameNoticeStart", new object[] {
                        taskid,
                        area,
                        msg});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GameNoticeStartAsync(string taskid, string area, string msg) {
            this.GameNoticeStartAsync(taskid, area, msg, null);
        }
        
        /// <remarks/>
        public void GameNoticeStartAsync(string taskid, string area, string msg, object userState) {
            if ((this.GameNoticeStartOperationCompleted == null)) {
                this.GameNoticeStartOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGameNoticeStartOperationCompleted);
            }
            this.InvokeAsync("GameNoticeStart", new object[] {
                        taskid,
                        area,
                        msg}, this.GameNoticeStartOperationCompleted, userState);
        }
        
        private void OnGameNoticeStartOperationCompleted(object arg) {
            if ((this.GameNoticeStartCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GameNoticeStartCompleted(this, new GameNoticeStartCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GameGiftAwardDo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GameGiftAwardDo(string taskid, string giftid, string gifttype, string giftnum, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] byteuser) {
            object[] results = this.Invoke("GameGiftAwardDo", new object[] {
                        taskid,
                        giftid,
                        gifttype,
                        giftnum,
                        byteuser});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GameGiftAwardDoAsync(string taskid, string giftid, string gifttype, string giftnum, byte[] byteuser) {
            this.GameGiftAwardDoAsync(taskid, giftid, gifttype, giftnum, byteuser, null);
        }
        
        /// <remarks/>
        public void GameGiftAwardDoAsync(string taskid, string giftid, string gifttype, string giftnum, byte[] byteuser, object userState) {
            if ((this.GameGiftAwardDoOperationCompleted == null)) {
                this.GameGiftAwardDoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGameGiftAwardDoOperationCompleted);
            }
            this.InvokeAsync("GameGiftAwardDo", new object[] {
                        taskid,
                        giftid,
                        gifttype,
                        giftnum,
                        byteuser}, this.GameGiftAwardDoOperationCompleted, userState);
        }
        
        private void OnGameGiftAwardDoOperationCompleted(object arg) {
            if ((this.GameGiftAwardDoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GameGiftAwardDoCompleted(this, new GameGiftAwardDoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GameGiftAwardDoFor5Num", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GameGiftAwardDoFor5Num(string taskid, string giftstr, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] byteuser) {
            object[] results = this.Invoke("GameGiftAwardDoFor5Num", new object[] {
                        taskid,
                        giftstr,
                        byteuser});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GameGiftAwardDoFor5NumAsync(string taskid, string giftstr, byte[] byteuser) {
            this.GameGiftAwardDoFor5NumAsync(taskid, giftstr, byteuser, null);
        }
        
        /// <remarks/>
        public void GameGiftAwardDoFor5NumAsync(string taskid, string giftstr, byte[] byteuser, object userState) {
            if ((this.GameGiftAwardDoFor5NumOperationCompleted == null)) {
                this.GameGiftAwardDoFor5NumOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGameGiftAwardDoFor5NumOperationCompleted);
            }
            this.InvokeAsync("GameGiftAwardDoFor5Num", new object[] {
                        taskid,
                        giftstr,
                        byteuser}, this.GameGiftAwardDoFor5NumOperationCompleted, userState);
        }
        
        private void OnGameGiftAwardDoFor5NumOperationCompleted(object arg) {
            if ((this.GameGiftAwardDoFor5NumCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GameGiftAwardDoFor5NumCompleted(this, new GameGiftAwardDoFor5NumCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GameGiftUserAdd", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GameGiftUserAdd(string userid, string roleid, string zoneid, string giftid, string giftnum, string note) {
            object[] results = this.Invoke("GameGiftUserAdd", new object[] {
                        userid,
                        roleid,
                        zoneid,
                        giftid,
                        giftnum,
                        note});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GameGiftUserAddAsync(string userid, string roleid, string zoneid, string giftid, string giftnum, string note) {
            this.GameGiftUserAddAsync(userid, roleid, zoneid, giftid, giftnum, note, null);
        }
        
        /// <remarks/>
        public void GameGiftUserAddAsync(string userid, string roleid, string zoneid, string giftid, string giftnum, string note, object userState) {
            if ((this.GameGiftUserAddOperationCompleted == null)) {
                this.GameGiftUserAddOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGameGiftUserAddOperationCompleted);
            }
            this.InvokeAsync("GameGiftUserAdd", new object[] {
                        userid,
                        roleid,
                        zoneid,
                        giftid,
                        giftnum,
                        note}, this.GameGiftUserAddOperationCompleted, userState);
        }
        
        private void OnGameGiftUserAddOperationCompleted(object arg) {
            if ((this.GameGiftUserAddCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GameGiftUserAddCompleted(this, new GameGiftUserAddCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteFullServiceEmail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DeleteFullServiceEmail(string taskid, string area, string msg) {
            object[] results = this.Invoke("DeleteFullServiceEmail", new object[] {
                        taskid,
                        area,
                        msg});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteFullServiceEmailAsync(string taskid, string area, string msg) {
            this.DeleteFullServiceEmailAsync(taskid, area, msg, null);
        }
        
        /// <remarks/>
        public void DeleteFullServiceEmailAsync(string taskid, string area, string msg, object userState) {
            if ((this.DeleteFullServiceEmailOperationCompleted == null)) {
                this.DeleteFullServiceEmailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteFullServiceEmailOperationCompleted);
            }
            this.InvokeAsync("DeleteFullServiceEmail", new object[] {
                        taskid,
                        area,
                        msg}, this.DeleteFullServiceEmailOperationCompleted, userState);
        }
        
        private void OnDeleteFullServiceEmailOperationCompleted(object arg) {
            if ((this.DeleteFullServiceEmailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteFullServiceEmailCompleted(this, new DeleteFullServiceEmailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddDisChat", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AddDisChat(string F_GUserID, string F_GRoleID, System.DateTime F_LimitTime) {
            object[] results = this.Invoke("AddDisChat", new object[] {
                        F_GUserID,
                        F_GRoleID,
                        F_LimitTime});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AddDisChatAsync(string F_GUserID, string F_GRoleID, System.DateTime F_LimitTime) {
            this.AddDisChatAsync(F_GUserID, F_GRoleID, F_LimitTime, null);
        }
        
        /// <remarks/>
        public void AddDisChatAsync(string F_GUserID, string F_GRoleID, System.DateTime F_LimitTime, object userState) {
            if ((this.AddDisChatOperationCompleted == null)) {
                this.AddDisChatOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddDisChatOperationCompleted);
            }
            this.InvokeAsync("AddDisChat", new object[] {
                        F_GUserID,
                        F_GRoleID,
                        F_LimitTime}, this.AddDisChatOperationCompleted, userState);
        }
        
        private void OnAddDisChatOperationCompleted(object arg) {
            if ((this.AddDisChatCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddDisChatCompleted(this, new AddDisChatCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void GetGameUsersCCompletedEventHandler(object sender, GetGameUsersCCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGameUsersCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGameUsersCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void GetGameRoleCRCompletedEventHandler(object sender, GetGameRoleCRCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGameRoleCRCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGameRoleCRCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void GetGameRoleCCompletedEventHandler(object sender, GetGameRoleCCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGameRoleCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGameRoleCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void GetZoneLineCompletedEventHandler(object sender, GetZoneLineCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetZoneLineCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetZoneLineCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void SetUserLockCompletedEventHandler(object sender, SetUserLockCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetUserLockCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetUserLockCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void SetRoleLockCompletedEventHandler(object sender, SetRoleLockCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetRoleLockCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetRoleLockCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void SetUserNoLockCompletedEventHandler(object sender, SetUserNoLockCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetUserNoLockCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetUserNoLockCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void SetRoleNoLockCompletedEventHandler(object sender, SetRoleNoLockCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetRoleNoLockCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetRoleNoLockCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void GetLockInfoCompletedEventHandler(object sender, GetLockInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLockInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLockInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void SetUserGMUseCompletedEventHandler(object sender, SetUserGMUseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetUserGMUseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetUserGMUseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void SetUserGMBackCompletedEventHandler(object sender, SetUserGMBackCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetUserGMBackCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetUserGMBackCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void RoleNameChangeCompletedEventHandler(object sender, RoleNameChangeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RoleNameChangeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RoleNameChangeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void RoleZoneChangeCompletedEventHandler(object sender, RoleZoneChangeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RoleZoneChangeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RoleZoneChangeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void UserRoleClearOnlineCompletedEventHandler(object sender, UserRoleClearOnlineCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UserRoleClearOnlineCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UserRoleClearOnlineCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void ClearChildDisInfoCompletedEventHandler(object sender, ClearChildDisInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ClearChildDisInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ClearChildDisInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void GameNoticeStopCompletedEventHandler(object sender, GameNoticeStopCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GameNoticeStopCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GameNoticeStopCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void GameNoticeStartCompletedEventHandler(object sender, GameNoticeStartCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GameNoticeStartCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GameNoticeStartCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void GameGiftAwardDoCompletedEventHandler(object sender, GameGiftAwardDoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GameGiftAwardDoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GameGiftAwardDoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void GameGiftAwardDoFor5NumCompletedEventHandler(object sender, GameGiftAwardDoFor5NumCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GameGiftAwardDoFor5NumCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GameGiftAwardDoFor5NumCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void GameGiftUserAddCompletedEventHandler(object sender, GameGiftUserAddCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GameGiftUserAddCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GameGiftUserAddCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void DeleteFullServiceEmailCompletedEventHandler(object sender, DeleteFullServiceEmailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteFullServiceEmailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteFullServiceEmailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void AddDisChatCompletedEventHandler(object sender, AddDisChatCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddDisChatCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddDisChatCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591