//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Global", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 名称允许输入16个字符（8个中文字符） 的本地化字符串。
        /// </summary>
        internal static string BattleZoneInputLimit {
            get {
                return ResourceManager.GetString("BattleZoneInputLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户端类型 的本地化字符串。
        /// </summary>
        internal static string ClientType {
            get {
                return ResourceManager.GetString("ClientType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前程序版本 的本地化字符串。
        /// </summary>
        internal static string FormulaVersionsCur {
            get {
                return ResourceManager.GetString("FormulaVersionsCur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 能进入程序最低版本 的本地化字符串。
        /// </summary>
        internal static string FormulaVersionsLow {
            get {
                return ResourceManager.GetString("FormulaVersionsLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前资源版本 的本地化字符串。
        /// </summary>
        internal static string FResourceVersionsCur {
            get {
                return ResourceManager.GetString("FResourceVersionsCur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 能进入资源最低版本 的本地化字符串。
        /// </summary>
        internal static string FResourceVersionsLow {
            get {
                return ResourceManager.GetString("FResourceVersionsLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进入程序最低版本[Android] 的本地化字符串。
        /// </summary>
        internal static string F_FaVersionsLow_And {
            get {
                return ResourceManager.GetString("F_FaVersionsLow_And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进入程序最低版本[IOS] 的本地化字符串。
        /// </summary>
        internal static string F_FaVersionsLow_Ios {
            get {
                return ResourceManager.GetString("F_FaVersionsLow_Ios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 能进入资源最低版本【Android】 的本地化字符串。
        /// </summary>
        internal static string F_ReVersionsLow_And {
            get {
                return ResourceManager.GetString("F_ReVersionsLow_And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 能进入资源最低版本【IOS】 的本地化字符串。
        /// </summary>
        internal static string F_ReVersionsLow_Ios {
            get {
                return ResourceManager.GetString("F_ReVersionsLow_Ios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 混服 的本地化字符串。
        /// </summary>
        internal static string ServerType_Mixed {
            get {
                return ResourceManager.GetString("ServerType_Mixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不限 的本地化字符串。
        /// </summary>
        internal static string ServerType_NoLimit {
            get {
                return ResourceManager.GetString("ServerType_NoLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        internal static string StringAdd {
            get {
                return ResourceManager.GetString("StringAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统警告 的本地化字符串。
        /// </summary>
        internal static string StringAlertTitle {
            get {
                return ResourceManager.GetString("StringAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所属大区 的本地化字符串。
        /// </summary>
        internal static string StringBigZoneID {
            get {
                return ResourceManager.GetString("StringBigZoneID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第一大区 的本地化字符串。
        /// </summary>
        internal static string StringBigZoneID0 {
            get {
                return ResourceManager.GetString("StringBigZoneID0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第二大区 的本地化字符串。
        /// </summary>
        internal static string StringBigZoneID1 {
            get {
                return ResourceManager.GetString("StringBigZoneID1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 阵营(国家) 的本地化字符串。
        /// </summary>
        internal static string StringCampID {
            get {
                return ResourceManager.GetString("StringCampID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 国家一 的本地化字符串。
        /// </summary>
        internal static string StringCampID0 {
            get {
                return ResourceManager.GetString("StringCampID0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 国家二 的本地化字符串。
        /// </summary>
        internal static string StringCampID1 {
            get {
                return ResourceManager.GetString("StringCampID1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收费类型 的本地化字符串。
        /// </summary>
        internal static string StringChargeType {
            get {
                return ResourceManager.GetString("StringChargeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 免费 的本地化字符串。
        /// </summary>
        internal static string StringChargeType0 {
            get {
                return ResourceManager.GetString("StringChargeType0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收费 的本地化字符串。
        /// </summary>
        internal static string StringChargeType1 {
            get {
                return ResourceManager.GetString("StringChargeType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提交成功 的本地化字符串。
        /// </summary>
        internal static string StringCommitDone {
            get {
                return ResourceManager.GetString("StringCommitDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据保存成功 的本地化字符串。
        /// </summary>
        internal static string StringCommitDoneT {
            get {
                return ResourceManager.GetString("StringCommitDoneT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提交失败 的本地化字符串。
        /// </summary>
        internal static string StringCommitFailed {
            get {
                return ResourceManager.GetString("StringCommitFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前版本 的本地化字符串。
        /// </summary>
        internal static string StringCurVersion {
            get {
                return ResourceManager.GetString("StringCurVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除选中行 的本地化字符串。
        /// </summary>
        internal static string StringDelete {
            get {
                return ResourceManager.GetString("StringDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏参数配置 的本地化字符串。
        /// </summary>
        internal static string StringGameConfig {
            get {
                return ResourceManager.GetString("StringGameConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GameConfig键 的本地化字符串。
        /// </summary>
        internal static string StringGameKey {
            get {
                return ResourceManager.GetString("StringGameKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 描述 的本地化字符串。
        /// </summary>
        internal static string StringGameNote {
            get {
                return ResourceManager.GetString("StringGameNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 简单升级文件配置 的本地化字符串。
        /// </summary>
        internal static string StringGameSimpleVersionListConfig {
            get {
                return ResourceManager.GetString("StringGameSimpleVersionListConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值 的本地化字符串。
        /// </summary>
        internal static string StringGameValue {
            get {
                return ResourceManager.GetString("StringGameValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 升级文件配置 的本地化字符串。
        /// </summary>
        internal static string StringGameVersionListConfig {
            get {
                return ResourceManager.GetString("StringGameVersionListConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前版本 的本地化字符串。
        /// </summary>
        internal static string StringGameVersionListCurVer {
            get {
                return ResourceManager.GetString("StringGameVersionListCurVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 降级文件大小 的本地化字符串。
        /// </summary>
        internal static string StringGameVersionListDownFileSize {
            get {
                return ResourceManager.GetString("StringGameVersionListDownFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件名 的本地化字符串。
        /// </summary>
        internal static string StringGameVersionListFileName {
            get {
                return ResourceManager.GetString("StringGameVersionListFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编号 的本地化字符串。
        /// </summary>
        internal static string StringGameVersionListID {
            get {
                return ResourceManager.GetString("StringGameVersionListID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 低版本(从哪个版本升级) 的本地化字符串。
        /// </summary>
        internal static string StringGameVersionListLowVer {
            get {
                return ResourceManager.GetString("StringGameVersionListLowVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间 的本地化字符串。
        /// </summary>
        internal static string StringGameVersionListTime {
            get {
                return ResourceManager.GetString("StringGameVersionListTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 升级文件大小 的本地化字符串。
        /// </summary>
        internal static string StringGameVersionListUpFileSize {
            get {
                return ResourceManager.GetString("StringGameVersionListUpFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GameServer配置 的本地化字符串。
        /// </summary>
        internal static string StringGSConfig {
            get {
                return ResourceManager.GetString("StringGSConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GS编号 的本地化字符串。
        /// </summary>
        internal static string StringGSID {
            get {
                return ResourceManager.GetString("StringGSID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GSIP地址 的本地化字符串。
        /// </summary>
        internal static string StringGSIP {
            get {
                return ResourceManager.GetString("StringGSIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GS名称 的本地化字符串。
        /// </summary>
        internal static string StringGSName {
            get {
                return ResourceManager.GetString("StringGSName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接的NGS(战区) 的本地化字符串。
        /// </summary>
        internal static string StringGSNGSID {
            get {
                return ResourceManager.GetString("StringGSNGSID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GS场景编 的本地化字符串。
        /// </summary>
        internal static string StringGSSceneID {
            get {
                return ResourceManager.GetString("StringGSSceneID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据发生改变您未保存。您确定要加载/刷新数据？ 的本地化字符串。
        /// </summary>
        internal static string StringIsRefresh {
            get {
                return ResourceManager.GetString("StringIsRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定要删除选中记录 的本地化字符串。
        /// </summary>
        internal static string StringIsToDelete {
            get {
                return ResourceManager.GetString("StringIsToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 战线配置 的本地化字符串。
        /// </summary>
        internal static string StringLineConfig {
            get {
                return ResourceManager.GetString("StringLineConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接DBIS的编号 的本地化字符串。
        /// </summary>
        internal static string StringLineDBISID {
            get {
                return ResourceManager.GetString("StringLineDBISID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网关服务器IP 的本地化字符串。
        /// </summary>
        internal static string StringLineIP {
            get {
                return ResourceManager.GetString("StringLineIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最大允许在线人数 的本地化字符串。
        /// </summary>
        internal static string StringLineMaxUser {
            get {
                return ResourceManager.GetString("StringLineMaxUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 战线名称 的本地化字符串。
        /// </summary>
        internal static string StringLineName {
            get {
                return ResourceManager.GetString("StringLineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NGS编号 的本地化字符串。
        /// </summary>
        internal static string StringLineNGSID {
            get {
                return ResourceManager.GetString("StringLineNGSID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PING的端口 的本地化字符串。
        /// </summary>
        internal static string StringLinePingPort {
            get {
                return ResourceManager.GetString("StringLinePingPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网关服务器端口 的本地化字符串。
        /// </summary>
        internal static string StringLinePort {
            get {
                return ResourceManager.GetString("StringLinePort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前状态 的本地化字符串。
        /// </summary>
        internal static string StringLineState {
            get {
                return ResourceManager.GetString("StringLineState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        internal static string StringLineState0 {
            get {
                return ResourceManager.GetString("StringLineState0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开启 的本地化字符串。
        /// </summary>
        internal static string StringLineState1 {
            get {
                return ResourceManager.GetString("StringLineState1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对内调试 对外关闭 的本地化字符串。
        /// </summary>
        internal static string StringLineState2 {
            get {
                return ResourceManager.GetString("StringLineState2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对内调试 对外隐藏 的本地化字符串。
        /// </summary>
        internal static string StringLineState3 {
            get {
                return ResourceManager.GetString("StringLineState3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所属战区 的本地化字符串。
        /// </summary>
        internal static string StringLineZoneID {
            get {
                return ResourceManager.GetString("StringLineZoneID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载失败 的本地化字符串。
        /// </summary>
        internal static string StringLoadException {
            get {
                return ResourceManager.GetString("StringLoadException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在执行,请稍候... 的本地化字符串。
        /// </summary>
        internal static string StringLoadingNow {
            get {
                return ResourceManager.GetString("StringLoadingNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登陆 的本地化字符串。
        /// </summary>
        internal static string StringLogin {
            get {
                return ResourceManager.GetString("StringLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击退出工具 的本地化字符串。
        /// </summary>
        internal static string StringLogOut {
            get {
                return ResourceManager.GetString("StringLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出工具准备中... 的本地化字符串。
        /// </summary>
        internal static string StringLogOutLoading {
            get {
                return ResourceManager.GetString("StringLogOutLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 否 的本地化字符串。
        /// </summary>
        internal static string StringNo {
            get {
                return ResourceManager.GetString("StringNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有信息可显示 的本地化字符串。
        /// </summary>
        internal static string StringNoInfo {
            get {
                return ResourceManager.GetString("StringNoInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 战区压力状态 的本地化字符串。
        /// </summary>
        internal static string StringPressState {
            get {
                return ResourceManager.GetString("StringPressState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 轻松 的本地化字符串。
        /// </summary>
        internal static string StringPressState0 {
            get {
                return ResourceManager.GetString("StringPressState0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拥挤 的本地化字符串。
        /// </summary>
        internal static string StringPressState1 {
            get {
                return ResourceManager.GetString("StringPressState1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 繁忙 的本地化字符串。
        /// </summary>
        internal static string StringPressState2 {
            get {
                return ResourceManager.GetString("StringPressState2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 爆满 的本地化字符串。
        /// </summary>
        internal static string StringPressState3 {
            get {
                return ResourceManager.GetString("StringPressState3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新 的本地化字符串。
        /// </summary>
        internal static string StringRefresh {
            get {
                return ResourceManager.GetString("StringRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重填 的本地化字符串。
        /// </summary>
        internal static string StringReset {
            get {
                return ResourceManager.GetString("StringReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        internal static string StringSave {
            get {
                return ResourceManager.GetString("StringSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存失败 的本地化字符串。
        /// </summary>
        internal static string StringSaveException {
            get {
                return ResourceManager.GetString("StringSaveException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 战区架设工具 的本地化字符串。
        /// </summary>
        internal static string StringSysTitle {
            get {
                return ResourceManager.GetString("StringSysTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 战区架设工具：双击单元格可进入编辑状态；如果输入有误会有红色边框或波浪线显示,鼠标移至上面会有原因提示；增删改后需点击保存才会生效（可批量保存） 的本地化字符串。
        /// </summary>
        internal static string StringToolTipsN {
            get {
                return ResourceManager.GetString("StringToolTipsN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 描述 的本地化字符串。
        /// </summary>
        internal static string StringToolTipsT {
            get {
                return ResourceManager.GetString("StringToolTipsT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证码 的本地化字符串。
        /// </summary>
        internal static string StringUserAuthCode {
            get {
                return ResourceManager.GetString("StringUserAuthCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 需要输入验证码 的本地化字符串。
        /// </summary>
        internal static string StringUserAuthCodeN {
            get {
                return ResourceManager.GetString("StringUserAuthCodeN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 鼠标移上来出现验证码 的本地化字符串。
        /// </summary>
        internal static string StringUserAuthCodeTip {
            get {
                return ResourceManager.GetString("StringUserAuthCodeTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户登录 的本地化字符串。
        /// </summary>
        internal static string StringUserLogin {
            get {
                return ResourceManager.GetString("StringUserLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名 的本地化字符串。
        /// </summary>
        internal static string StringUserName {
            get {
                return ResourceManager.GetString("StringUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 需要输入用户名 的本地化字符串。
        /// </summary>
        internal static string StringUserNameN {
            get {
                return ResourceManager.GetString("StringUserNameN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密     码 的本地化字符串。
        /// </summary>
        internal static string StringUserPSW {
            get {
                return ResourceManager.GetString("StringUserPSW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 需要输入密码 的本地化字符串。
        /// </summary>
        internal static string StringUserPSWN {
            get {
                return ResourceManager.GetString("StringUserPSWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是 的本地化字符串。
        /// </summary>
        internal static string StringYes {
            get {
                return ResourceManager.GetString("StringYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新开战区 的本地化字符串。
        /// </summary>
        internal static string StringZoneAttrib0 {
            get {
                return ResourceManager.GetString("StringZoneAttrib0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 推荐战区 的本地化字符串。
        /// </summary>
        internal static string StringZoneAttrib1 {
            get {
                return ResourceManager.GetString("StringZoneAttrib1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 战区经验 的本地化字符串。
        /// </summary>
        internal static string StringZoneAttrib2 {
            get {
                return ResourceManager.GetString("StringZoneAttrib2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正常经验 的本地化字符串。
        /// </summary>
        internal static string StringZoneAttrib20 {
            get {
                return ResourceManager.GetString("StringZoneAttrib20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2倍经验 的本地化字符串。
        /// </summary>
        internal static string StringZoneAttrib21 {
            get {
                return ResourceManager.GetString("StringZoneAttrib21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 4倍经验 的本地化字符串。
        /// </summary>
        internal static string StringZoneAttrib22 {
            get {
                return ResourceManager.GetString("StringZoneAttrib22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 8倍经验 的本地化字符串。
        /// </summary>
        internal static string StringZoneAttrib23 {
            get {
                return ResourceManager.GetString("StringZoneAttrib23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 火爆战区 的本地化字符串。
        /// </summary>
        internal static string StringZoneAttrib4 {
            get {
                return ResourceManager.GetString("StringZoneAttrib4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 战区配置 的本地化字符串。
        /// </summary>
        internal static string StringZoneConfig {
            get {
                return ResourceManager.GetString("StringZoneConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 战区编号 的本地化字符串。
        /// </summary>
        internal static string StringZoneID {
            get {
                return ResourceManager.GetString("StringZoneID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网络线路 的本地化字符串。
        /// </summary>
        internal static string StringZoneLine {
            get {
                return ResourceManager.GetString("StringZoneLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网通 的本地化字符串。
        /// </summary>
        internal static string StringZoneLine0 {
            get {
                return ResourceManager.GetString("StringZoneLine0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电信 的本地化字符串。
        /// </summary>
        internal static string StringZoneLine1 {
            get {
                return ResourceManager.GetString("StringZoneLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 双线 的本地化字符串。
        /// </summary>
        internal static string StringZoneLine2 {
            get {
                return ResourceManager.GetString("StringZoneLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 战区名称 的本地化字符串。
        /// </summary>
        internal static string StringZoneName {
            get {
                return ResourceManager.GetString("StringZoneName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 战区状态 的本地化字符串。
        /// </summary>
        internal static string StringZoneState {
            get {
                return ResourceManager.GetString("StringZoneState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 战区关闭 的本地化字符串。
        /// </summary>
        internal static string StringZoneState0 {
            get {
                return ResourceManager.GetString("StringZoneState0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 战区开放 的本地化字符串。
        /// </summary>
        internal static string StringZoneState1 {
            get {
                return ResourceManager.GetString("StringZoneState1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知 的本地化字符串。
        /// </summary>
        internal static string StringZoneState2 {
            get {
                return ResourceManager.GetString("StringZoneState2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测试状态 的本地化字符串。
        /// </summary>
        internal static string StringZoneTestState {
            get {
                return ResourceManager.GetString("StringZoneTestState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正常状态 的本地化字符串。
        /// </summary>
        internal static string StringZoneTestState0 {
            get {
                return ResourceManager.GetString("StringZoneTestState0", resourceCulture);
            }
        }
    }
}
