//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSSServer.LanguageResource {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GSSServer.LanguageResource.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 请求接收失败。 的本地化字符串。
        /// </summary>
        internal static string Tip_ClientRequestLack {
            get {
                return ResourceManager.GetString("Tip_ClientRequestLack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单创建失败! 的本地化字符串。
        /// </summary>
        internal static string Tip_CreateWorkOrderFailure {
            get {
                return ResourceManager.GetString("Tip_CreateWorkOrderFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编号应该大于0 的本地化字符串。
        /// </summary>
        internal static string Tip_IDShouldGatherThan0 {
            get {
                return ResourceManager.GetString("Tip_IDShouldGatherThan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统缺少远程数据库【{0}】连接实例名 的本地化字符串。
        /// </summary>
        internal static string Tip_LinkServerStatue_4041 {
            get {
                return ResourceManager.GetString("Tip_LinkServerStatue_4041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统建立的远程数据库MySQL【{0}】连接没有保留连接串 的本地化字符串。
        /// </summary>
        internal static string Tip_LinkServerStatue_4043 {
            get {
                return ResourceManager.GetString("Tip_LinkServerStatue_4043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统缺少远程连接ZoneRoleDataDB实例名 的本地化字符串。
        /// </summary>
        internal static string Tip_RecoverRoleStatue_4042 {
            get {
                return ResourceManager.GetString("Tip_RecoverRoleStatue_4042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 待恢复角色位置在角色栏已被其他角色使用。 的本地化字符串。
        /// </summary>
        internal static string Tip_RecoveryRoleStatue_1 {
            get {
                return ResourceManager.GetString("Tip_RecoveryRoleStatue_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该角色状态正常，本次不需要进行恢复，或者刷新数据查看状态。 的本地化字符串。
        /// </summary>
        internal static string Tip_RecoveryRoleStatue_2 {
            get {
                return ResourceManager.GetString("Tip_RecoveryRoleStatue_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统缺少远程数据库GameCoreDB连接实例名 的本地化字符串。
        /// </summary>
        internal static string Tip_RecoveryRoleStatue_4041 {
            get {
                return ResourceManager.GetString("Tip_RecoveryRoleStatue_4041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请求成功 的本地化字符串。
        /// </summary>
        internal static string Tip_RequestSuccess {
            get {
                return ResourceManager.GetString("Tip_RequestSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器缺少模板文件【{0}】 的本地化字符串。
        /// </summary>
        internal static string Tip_ServiceLackTemplateFormat {
            get {
                return ResourceManager.GetString("Tip_ServiceLackTemplateFormat", resourceCulture);
            }
        }
    }
}
